// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type HomepageDocumentDataSlicesSlice =
  | WhyUsSlice
  | VisionMissionSlice
  | ServicesColoredSectionSlice
  | ContentWithTwoImagesSlice
  | EngageWithUsSlice
  | IndustriesOfInterestSlice
  | TeamIndexSlice
  | SlideShowSlice
  | TestimonialsSlice
  | CoreValuesSlice
  | ColorBackgroundSlice
  | MemberBioSliceSlice
  | FocusSectorsSlice
  | InsightIndexSlice
  | FaqSliceSlice
  | ContentHeadingSlice
  | FeaturedImageSlice
  | ContactHeroSlice
  | ContactFormSlice
  | WhyChooseUsSlice
  | ServicesSlice
  | ImageBackgroundSlice
  | HeroSlice
  | CallToActionSlice
  | VideoBackgroundSlice;

/**
 * Content for HomePage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *HomePage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *HomePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *HomePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *HomePage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * HomePage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

type InsightDocumentDataSlicesSlice =
  | ContactFormSlice
  | EngageWithUsSlice
  | ServicesSidebarContentSlice
  | OneImageBackgroundSlice
  | IndustriesOfInterestSlice
  | CoreValuesSlice
  | ImageBackgroundSlice
  | VideoBackgroundSlice
  | WhyChooseUsSlice
  | ServicesSlice
  | CallToActionSlice
  | HeroSlice
  | FeaturedImageSlice
  | ContentHeadingSlice
  | FaqSliceSlice
  | ContactHeroSlice;

/**
 * Content for Insight documents
 */
interface InsightDocumentData {
  /**
   * Title field in *Insight*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: insight.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Tag field in *Insight*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: insight.tag
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tag: prismic.KeyTextField;

  /**
   * Description field in *Insight*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: insight.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Featured Image field in *Insight*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: insight.featured_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  featured_image: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Insight*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: insight.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<InsightDocumentDataSlicesSlice> /**
   * Meta Title field in *Insight*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: insight.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Insight*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: insight.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Insight*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: insight.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Insight document from Prismic
 *
 * - **API ID**: `insight`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type InsightDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<InsightDocumentData>,
    "insight",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | TestimonialsSidebarContentSlice
  | FaqSidebarContentSlice
  | CoreValuesSidebarContentSlice
  | EngageSidebarContentSlice
  | ServicesSidebarContentSlice
  | SidebarContentSlice
  | SlideShowSlice
  | OneImageBackgroundSlice
  | ServicesColoredSectionSlice
  | ContentWithTwoImagesSlice
  | IndustriesOfInterestSlice
  | WhyUsSlice
  | EngageWithUsSlice
  | VisionMissionSlice
  | TeamIndexSlice
  | TestimonialsSlice
  | CoreValuesSlice
  | ColorBackgroundSlice
  | MemberBioSliceSlice
  | FocusSectorsSlice
  | InsightIndexSlice
  | FaqSliceSlice
  | ContentHeadingSlice
  | FeaturedImageSlice
  | ContactHeroSlice
  | ContactFormSlice
  | WhyChooseUsSlice
  | ServicesSlice
  | ImageBackgroundSlice
  | HeroSlice
  | CallToActionSlice
  | VideoBackgroundSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

type ServiceDocumentDataSlicesSlice =
  | OneImageBackgroundSlice
  | ServicesSidebarContentSlice
  | SlideShowSlice
  | SidebarContentSlice
  | ServicesColoredSectionSlice
  | EngageWithUsSlice
  | TeamIndexSlice
  | TestimonialsSlice
  | MemberBioSliceSlice
  | IndustriesOfInterestSlice
  | ColorBackgroundSlice
  | ContentWithTwoImagesSlice
  | CoreValuesSlice
  | FocusSectorsSlice
  | ImageBackgroundSlice
  | InsightIndexSlice
  | FaqSliceSlice
  | VideoBackgroundSlice
  | ContentHeadingSlice
  | WhyChooseUsSlice
  | ContactHeroSlice
  | FeaturedImageSlice
  | ServicesSlice
  | HeroSlice
  | ContactFormSlice
  | CallToActionSlice;

/**
 * Content for Service documents
 */
interface ServiceDocumentData {
  /**
   * Slice Zone field in *Service*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: service.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ServiceDocumentDataSlicesSlice> /**
   * Meta Title field in *Service*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: service.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Service*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: service.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Service*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Service document from Prismic
 *
 * - **API ID**: `service`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ServiceDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ServiceDocumentData>,
    "service",
    Lang
  >;

export type AllDocumentTypes =
  | HomepageDocument
  | InsightDocument
  | PageDocument
  | ServiceDocument;

/**
 * Primary content in *CallToAction → Default → Primary*
 */
export interface CallToActionSliceDefaultPrimary {
  /**
   * Heading field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Tagline field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.default.primary.tagline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tagline: prismic.KeyTextField;

  /**
   * Cta Link field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.default.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for CallToAction Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CallToActionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CallToAction*
 */
type CallToActionSliceVariation = CallToActionSliceDefault;

/**
 * CallToAction Shared Slice
 *
 * - **API ID**: `call_to_action`
 * - **Description**: CallToAction
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSlice = prismic.SharedSlice<
  "call_to_action",
  CallToActionSliceVariation
>;

/**
 * Primary content in *ColorBackground → Default → Primary*
 */
export interface ColorBackgroundSliceDefaultPrimary {
  /**
   * Title field in *ColorBackground → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: color_background.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Content field in *ColorBackground → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: color_background.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Tagline field in *ColorBackground → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: color_background.default.primary.tagline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tagline: prismic.KeyTextField;
}

/**
 * Default variation for ColorBackground Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ColorBackgroundSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ColorBackgroundSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ColorBackground*
 */
type ColorBackgroundSliceVariation = ColorBackgroundSliceDefault;

/**
 * ColorBackground Shared Slice
 *
 * - **API ID**: `color_background`
 * - **Description**: ColorBackground
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ColorBackgroundSlice = prismic.SharedSlice<
  "color_background",
  ColorBackgroundSliceVariation
>;

/**
 * Default variation for ContactForm Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactFormSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *ContactForm*
 */
type ContactFormSliceVariation = ContactFormSliceDefault;

/**
 * ContactForm Shared Slice
 *
 * - **API ID**: `contact_form`
 * - **Description**: ContactForm
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactFormSlice = prismic.SharedSlice<
  "contact_form",
  ContactFormSliceVariation
>;

/**
 * Default variation for ContactHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactHeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *ContactHero*
 */
type ContactHeroSliceVariation = ContactHeroSliceDefault;

/**
 * ContactHero Shared Slice
 *
 * - **API ID**: `contact_hero`
 * - **Description**: ContactHero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactHeroSlice = prismic.SharedSlice<
  "contact_hero",
  ContactHeroSliceVariation
>;

/**
 * Primary content in *ContentHeading → Default → Primary*
 */
export interface ContentHeadingSliceDefaultPrimary {
  /**
   * Heading field in *ContentHeading → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_heading.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * content field in *ContentHeading → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_heading.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Tagline field in *ContentHeading → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_heading.default.primary.tagline
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  tagline: prismic.RichTextField;
}

/**
 * Default variation for ContentHeading Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentHeadingSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContentHeadingSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *ContentHeading → Content With Left Heading → Primary*
 */
export interface ContentHeadingSliceContentWithLeftHeadingPrimary {
  /**
   * Heading field in *ContentHeading → Content With Left Heading → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_heading.contentWithLeftHeading.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * content field in *ContentHeading → Content With Left Heading → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_heading.contentWithLeftHeading.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Tagline field in *ContentHeading → Content With Left Heading → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_heading.contentWithLeftHeading.primary.tagline
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  tagline: prismic.RichTextField;

  /**
   * Background Image field in *ContentHeading → Content With Left Heading → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: content_heading.contentWithLeftHeading.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;
}

/**
 * Content With Left Heading variation for ContentHeading Slice
 *
 * - **API ID**: `contentWithLeftHeading`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentHeadingSliceContentWithLeftHeading =
  prismic.SharedSliceVariation<
    "contentWithLeftHeading",
    Simplify<ContentHeadingSliceContentWithLeftHeadingPrimary>,
    never
  >;

/**
 * Slice variation for *ContentHeading*
 */
type ContentHeadingSliceVariation =
  | ContentHeadingSliceDefault
  | ContentHeadingSliceContentWithLeftHeading;

/**
 * ContentHeading Shared Slice
 *
 * - **API ID**: `content_heading`
 * - **Description**: ContentHeading
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentHeadingSlice = prismic.SharedSlice<
  "content_heading",
  ContentHeadingSliceVariation
>;

/**
 * Primary content in *ContentWithTwoImages → Default → Primary*
 */
export interface ContentWithTwoImagesSliceDefaultPrimary {
  /**
   * Content field in *ContentWithTwoImages → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_with_two_images.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * First Image field in *ContentWithTwoImages → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: content_with_two_images.default.primary.first_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  first_image: prismic.ImageField<never>;

  /**
   * Second Image field in *ContentWithTwoImages → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: content_with_two_images.default.primary.second_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  second_image: prismic.ImageField<never>;
}

/**
 * Default variation for ContentWithTwoImages Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentWithTwoImagesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContentWithTwoImagesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContentWithTwoImages*
 */
type ContentWithTwoImagesSliceVariation = ContentWithTwoImagesSliceDefault;

/**
 * ContentWithTwoImages Shared Slice
 *
 * - **API ID**: `content_with_two_images`
 * - **Description**: ContentWithTwoImages
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentWithTwoImagesSlice = prismic.SharedSlice<
  "content_with_two_images",
  ContentWithTwoImagesSliceVariation
>;

/**
 * Default variation for CoreValues Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CoreValuesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *CoreValues*
 */
type CoreValuesSliceVariation = CoreValuesSliceDefault;

/**
 * CoreValues Shared Slice
 *
 * - **API ID**: `core_values`
 * - **Description**: CoreValues
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CoreValuesSlice = prismic.SharedSlice<
  "core_values",
  CoreValuesSliceVariation
>;

/**
 * Default variation for CoreValuesSidebarContent Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CoreValuesSidebarContentSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *CoreValuesSidebarContent*
 */
type CoreValuesSidebarContentSliceVariation =
  CoreValuesSidebarContentSliceDefault;

/**
 * CoreValuesSidebarContent Shared Slice
 *
 * - **API ID**: `core_values_sidebar_content`
 * - **Description**: CoreValuesSidebarContent
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CoreValuesSidebarContentSlice = prismic.SharedSlice<
  "core_values_sidebar_content",
  CoreValuesSidebarContentSliceVariation
>;

/**
 * Default variation for EngageSidebarContent Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EngageSidebarContentSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *EngageSidebarContent*
 */
type EngageSidebarContentSliceVariation = EngageSidebarContentSliceDefault;

/**
 * EngageSidebarContent Shared Slice
 *
 * - **API ID**: `engage_sidebar_content`
 * - **Description**: EngageSidebarContent
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EngageSidebarContentSlice = prismic.SharedSlice<
  "engage_sidebar_content",
  EngageSidebarContentSliceVariation
>;

/**
 * Default variation for EngageWithUs Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EngageWithUsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *EngageWithUs*
 */
type EngageWithUsSliceVariation = EngageWithUsSliceDefault;

/**
 * EngageWithUs Shared Slice
 *
 * - **API ID**: `engage_with_us`
 * - **Description**: EngageWithUs
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EngageWithUsSlice = prismic.SharedSlice<
  "engage_with_us",
  EngageWithUsSliceVariation
>;

/**
 * Default variation for FaqSidebarContent Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqSidebarContentSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *FaqSidebarContent*
 */
type FaqSidebarContentSliceVariation = FaqSidebarContentSliceDefault;

/**
 * FaqSidebarContent Shared Slice
 *
 * - **API ID**: `faq_sidebar_content`
 * - **Description**: FaqSidebarContent
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqSidebarContentSlice = prismic.SharedSlice<
  "faq_sidebar_content",
  FaqSidebarContentSliceVariation
>;

/**
 * Item in *FaqSlice → Default → Primary → Faq Questions*
 */
export interface FaqSliceSliceDefaultPrimaryFaqQuestionsItem {
  /**
   * Question field in *FaqSlice → Default → Primary → Faq Questions*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_slice.default.primary.faq_questions[].question
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  question: prismic.KeyTextField;

  /**
   * Answer field in *FaqSlice → Default → Primary → Faq Questions*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_slice.default.primary.faq_questions[].answer
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  answer: prismic.RichTextField;
}

/**
 * Primary content in *FaqSlice → Default → Primary*
 */
export interface FaqSliceSliceDefaultPrimary {
  /**
   * Heading field in *FaqSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_slice.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Tagline field in *FaqSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_slice.default.primary.tagline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tagline: prismic.KeyTextField;

  /**
   * Faq Questions field in *FaqSlice → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_slice.default.primary.faq_questions[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  faq_questions: prismic.GroupField<
    Simplify<FaqSliceSliceDefaultPrimaryFaqQuestionsItem>
  >;
}

/**
 * Default variation for FaqSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FaqSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FaqSlice*
 */
type FaqSliceSliceVariation = FaqSliceSliceDefault;

/**
 * FaqSlice Shared Slice
 *
 * - **API ID**: `faq_slice`
 * - **Description**: FaqSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqSliceSlice = prismic.SharedSlice<
  "faq_slice",
  FaqSliceSliceVariation
>;

/**
 * Primary content in *FeaturedImage → Default → Primary*
 */
export interface FeaturedImageSliceDefaultPrimary {
  /**
   * Main Image field in *FeaturedImage → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_image.default.primary.main_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  main_image: prismic.ImageField<never>;

  /**
   * Title field in *FeaturedImage → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_image.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Content field in *FeaturedImage → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_image.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for FeaturedImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeaturedImageSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FeaturedImage*
 */
type FeaturedImageSliceVariation = FeaturedImageSliceDefault;

/**
 * FeaturedImage Shared Slice
 *
 * - **API ID**: `featured_image`
 * - **Description**: FeaturedImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedImageSlice = prismic.SharedSlice<
  "featured_image",
  FeaturedImageSliceVariation
>;

/**
 * Default variation for FocusSectors Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FocusSectorsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *FocusSectors*
 */
type FocusSectorsSliceVariation = FocusSectorsSliceDefault;

/**
 * FocusSectors Shared Slice
 *
 * - **API ID**: `focus_sectors`
 * - **Description**: FocusSectors
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FocusSectorsSlice = prismic.SharedSlice<
  "focus_sectors",
  FocusSectorsSliceVariation
>;

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *ImageBackground → Default → Primary*
 */
export interface ImageBackgroundSliceDefaultPrimary {
  /**
   * Background Image field in *ImageBackground → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_background.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Heading field in *ImageBackground → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_background.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Tagline field in *ImageBackground → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_background.default.primary.tagline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tagline: prismic.KeyTextField;

  /**
   * PositionTop field in *ImageBackground → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: image_background.default.primary.positiontop
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  positiontop: prismic.BooleanField;
}

/**
 * Default variation for ImageBackground Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageBackgroundSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageBackgroundSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ImageBackground*
 */
type ImageBackgroundSliceVariation = ImageBackgroundSliceDefault;

/**
 * ImageBackground Shared Slice
 *
 * - **API ID**: `image_background`
 * - **Description**: ImageBackground
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageBackgroundSlice = prismic.SharedSlice<
  "image_background",
  ImageBackgroundSliceVariation
>;

/**
 * Default variation for IndustriesOfInterest Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IndustriesOfInterestSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *IndustriesOfInterest*
 */
type IndustriesOfInterestSliceVariation = IndustriesOfInterestSliceDefault;

/**
 * IndustriesOfInterest Shared Slice
 *
 * - **API ID**: `industries_of_interest`
 * - **Description**: IndustriesOfInterest
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IndustriesOfInterestSlice = prismic.SharedSlice<
  "industries_of_interest",
  IndustriesOfInterestSliceVariation
>;

/**
 * Default variation for InsightIndex Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InsightIndexSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *InsightIndex*
 */
type InsightIndexSliceVariation = InsightIndexSliceDefault;

/**
 * InsightIndex Shared Slice
 *
 * - **API ID**: `insight_index`
 * - **Description**: InsightIndex
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InsightIndexSlice = prismic.SharedSlice<
  "insight_index",
  InsightIndexSliceVariation
>;

/**
 * Primary content in *MemberBioSlice → Default → Primary*
 */
export interface MemberBioSliceSliceDefaultPrimary {
  /**
   * Member Name field in *MemberBioSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: member_bio_slice.default.primary.member_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  member_name: prismic.KeyTextField;

  /**
   * Designation field in *MemberBioSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: member_bio_slice.default.primary.designation
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  designation: prismic.KeyTextField;

  /**
   * Bio field in *MemberBioSlice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: member_bio_slice.default.primary.bio
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  bio: prismic.RichTextField;

  /**
   * Member Image field in *MemberBioSlice → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: member_bio_slice.default.primary.member_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  member_image: prismic.ImageField<never>;
}

/**
 * Default variation for MemberBioSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MemberBioSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MemberBioSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *MemberBioSlice*
 */
type MemberBioSliceSliceVariation = MemberBioSliceSliceDefault;

/**
 * MemberBioSlice Shared Slice
 *
 * - **API ID**: `member_bio_slice`
 * - **Description**: MemberBioSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MemberBioSliceSlice = prismic.SharedSlice<
  "member_bio_slice",
  MemberBioSliceSliceVariation
>;

/**
 * Primary content in *OneImageBackground → Default → Primary*
 */
export interface OneImageBackgroundSliceDefaultPrimary {
  /**
   * Background Image field in *OneImageBackground → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: one_image_background.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Heading field in *OneImageBackground → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: one_image_background.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;
}

/**
 * Default variation for OneImageBackground Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OneImageBackgroundSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<OneImageBackgroundSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *OneImageBackground*
 */
type OneImageBackgroundSliceVariation = OneImageBackgroundSliceDefault;

/**
 * OneImageBackground Shared Slice
 *
 * - **API ID**: `one_image_background`
 * - **Description**: OneImageBackground
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OneImageBackgroundSlice = prismic.SharedSlice<
  "one_image_background",
  OneImageBackgroundSliceVariation
>;

/**
 * Primary content in *Services → Default → Primary*
 */
export interface ServicesSliceDefaultPrimary {
  /**
   * Background Image field in *Services → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;
}

/**
 * Default variation for Services Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServicesSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Services → Services With Heading → Primary*
 */
export interface ServicesSliceServicesWithHeadingPrimary {
  /**
   * Background Image field in *Services → Services With Heading → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: services.servicesWithHeading.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Heading field in *Services → Services With Heading → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.servicesWithHeading.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;
}

/**
 * Services With Heading variation for Services Slice
 *
 * - **API ID**: `servicesWithHeading`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesSliceServicesWithHeading = prismic.SharedSliceVariation<
  "servicesWithHeading",
  Simplify<ServicesSliceServicesWithHeadingPrimary>,
  never
>;

/**
 * Slice variation for *Services*
 */
type ServicesSliceVariation =
  | ServicesSliceDefault
  | ServicesSliceServicesWithHeading;

/**
 * Services Shared Slice
 *
 * - **API ID**: `services`
 * - **Description**: Services
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesSlice = prismic.SharedSlice<
  "services",
  ServicesSliceVariation
>;

/**
 * Default variation for ServicesColoredSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesColoredSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *ServicesColoredSection*
 */
type ServicesColoredSectionSliceVariation = ServicesColoredSectionSliceDefault;

/**
 * ServicesColoredSection Shared Slice
 *
 * - **API ID**: `services_colored_section`
 * - **Description**: ServicesColoredSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesColoredSectionSlice = prismic.SharedSlice<
  "services_colored_section",
  ServicesColoredSectionSliceVariation
>;

/**
 * Primary content in *ServicesSidebarContent → Default → Primary*
 */
export interface ServicesSidebarContentSliceDefaultPrimary {
  /**
   * Main Content field in *ServicesSidebarContent → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_sidebar_content.default.primary.main_content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  main_content: prismic.RichTextField;
}

/**
 * Default variation for ServicesSidebarContent Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesSidebarContentSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServicesSidebarContentSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ServicesSidebarContent*
 */
type ServicesSidebarContentSliceVariation = ServicesSidebarContentSliceDefault;

/**
 * ServicesSidebarContent Shared Slice
 *
 * - **API ID**: `services_sidebar_content`
 * - **Description**: ServicesSidebarContent
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesSidebarContentSlice = prismic.SharedSlice<
  "services_sidebar_content",
  ServicesSidebarContentSliceVariation
>;

/**
 * Primary content in *SidebarContent → Default → Primary*
 */
export interface SidebarContentSliceDefaultPrimary {
  /**
   * Main Content field in *SidebarContent → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sidebar_content.default.primary.main_content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  main_content: prismic.RichTextField;

  /**
   * Title field in *SidebarContent → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sidebar_content.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Default variation for SidebarContent Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SidebarContentSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SidebarContentSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SidebarContent*
 */
type SidebarContentSliceVariation = SidebarContentSliceDefault;

/**
 * SidebarContent Shared Slice
 *
 * - **API ID**: `sidebar_content`
 * - **Description**: SidebarContent
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SidebarContentSlice = prismic.SharedSlice<
  "sidebar_content",
  SidebarContentSliceVariation
>;

/**
 * Default variation for SlideShow Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SlideShowSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *SlideShow*
 */
type SlideShowSliceVariation = SlideShowSliceDefault;

/**
 * SlideShow Shared Slice
 *
 * - **API ID**: `slide_show`
 * - **Description**: SlideShow
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SlideShowSlice = prismic.SharedSlice<
  "slide_show",
  SlideShowSliceVariation
>;

/**
 * Item in *TeamIndex → Default → Primary → Team Members*
 */
export interface TeamIndexSliceDefaultPrimaryTeamMembersItem {
  /**
   * Member Name field in *TeamIndex → Default → Primary → Team Members*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_index.default.primary.team_members[].member_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  member_name: prismic.KeyTextField;

  /**
   * Member Image field in *TeamIndex → Default → Primary → Team Members*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: team_index.default.primary.team_members[].member_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  member_image: prismic.ImageField<never>;

  /**
   * Linkedin Link field in *TeamIndex → Default → Primary → Team Members*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: team_index.default.primary.team_members[].linkedin_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkedin_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Member Designation field in *TeamIndex → Default → Primary → Team Members*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_index.default.primary.team_members[].member_designation
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  member_designation: prismic.KeyTextField;
}

/**
 * Primary content in *TeamIndex → Default → Primary*
 */
export interface TeamIndexSliceDefaultPrimary {
  /**
   * Team Members field in *TeamIndex → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: team_index.default.primary.team_members[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  team_members: prismic.GroupField<
    Simplify<TeamIndexSliceDefaultPrimaryTeamMembersItem>
  >;
}

/**
 * Default variation for TeamIndex Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamIndexSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TeamIndexSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TeamIndex*
 */
type TeamIndexSliceVariation = TeamIndexSliceDefault;

/**
 * TeamIndex Shared Slice
 *
 * - **API ID**: `team_index`
 * - **Description**: TeamIndex
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamIndexSlice = prismic.SharedSlice<
  "team_index",
  TeamIndexSliceVariation
>;

/**
 * Default variation for Testimonials Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Testimonials*
 */
type TestimonialsSliceVariation = TestimonialsSliceDefault;

/**
 * Testimonials Shared Slice
 *
 * - **API ID**: `testimonials`
 * - **Description**: Testimonials
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSlice = prismic.SharedSlice<
  "testimonials",
  TestimonialsSliceVariation
>;

/**
 * Default variation for TestimonialsSidebarContent Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSidebarContentSliceDefault =
  prismic.SharedSliceVariation<"default", Record<string, never>, never>;

/**
 * Slice variation for *TestimonialsSidebarContent*
 */
type TestimonialsSidebarContentSliceVariation =
  TestimonialsSidebarContentSliceDefault;

/**
 * TestimonialsSidebarContent Shared Slice
 *
 * - **API ID**: `testimonials_sidebar_content`
 * - **Description**: TestimonialsSidebarContent
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSidebarContentSlice = prismic.SharedSlice<
  "testimonials_sidebar_content",
  TestimonialsSidebarContentSliceVariation
>;

/**
 * Primary content in *VideoBackground → Default → Primary*
 */
export interface VideoBackgroundSliceDefaultPrimary {
  /**
   * Heading field in *VideoBackground → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video_background.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Tagline field in *VideoBackground → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video_background.default.primary.tagline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tagline: prismic.KeyTextField;
}

/**
 * Default variation for VideoBackground Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoBackgroundSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VideoBackgroundSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *VideoBackground*
 */
type VideoBackgroundSliceVariation = VideoBackgroundSliceDefault;

/**
 * VideoBackground Shared Slice
 *
 * - **API ID**: `video_background`
 * - **Description**: VideoBackground
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoBackgroundSlice = prismic.SharedSlice<
  "video_background",
  VideoBackgroundSliceVariation
>;

/**
 * Primary content in *VisionMission → Default → Primary*
 */
export interface VisionMissionSliceDefaultPrimary {
  /**
   * Background Image field in *VisionMission → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: vision_mission.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;
}

/**
 * Default variation for VisionMission Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VisionMissionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VisionMissionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *VisionMission*
 */
type VisionMissionSliceVariation = VisionMissionSliceDefault;

/**
 * VisionMission Shared Slice
 *
 * - **API ID**: `vision_mission`
 * - **Description**: VisionMission
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VisionMissionSlice = prismic.SharedSlice<
  "vision_mission",
  VisionMissionSliceVariation
>;

/**
 * Primary content in *WhyChooseUs → Default → Primary*
 */
export interface WhyChooseUsSliceDefaultPrimary {
  /**
   * Background Image field in *WhyChooseUs → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: why_choose_us.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;
}

/**
 * Default variation for WhyChooseUs Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WhyChooseUsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WhyChooseUsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *WhyChooseUs*
 */
type WhyChooseUsSliceVariation = WhyChooseUsSliceDefault;

/**
 * WhyChooseUs Shared Slice
 *
 * - **API ID**: `why_choose_us`
 * - **Description**: WhyChooseUs
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WhyChooseUsSlice = prismic.SharedSlice<
  "why_choose_us",
  WhyChooseUsSliceVariation
>;

/**
 * Default variation for WhyUs Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WhyUsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *WhyUs*
 */
type WhyUsSliceVariation = WhyUsSliceDefault;

/**
 * WhyUs Shared Slice
 *
 * - **API ID**: `why_us`
 * - **Description**: WhyUs
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WhyUsSlice = prismic.SharedSlice<"why_us", WhyUsSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      InsightDocument,
      InsightDocumentData,
      InsightDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      ServiceDocument,
      ServiceDocumentData,
      ServiceDocumentDataSlicesSlice,
      AllDocumentTypes,
      CallToActionSlice,
      CallToActionSliceDefaultPrimary,
      CallToActionSliceVariation,
      CallToActionSliceDefault,
      ColorBackgroundSlice,
      ColorBackgroundSliceDefaultPrimary,
      ColorBackgroundSliceVariation,
      ColorBackgroundSliceDefault,
      ContactFormSlice,
      ContactFormSliceVariation,
      ContactFormSliceDefault,
      ContactHeroSlice,
      ContactHeroSliceVariation,
      ContactHeroSliceDefault,
      ContentHeadingSlice,
      ContentHeadingSliceDefaultPrimary,
      ContentHeadingSliceContentWithLeftHeadingPrimary,
      ContentHeadingSliceVariation,
      ContentHeadingSliceDefault,
      ContentHeadingSliceContentWithLeftHeading,
      ContentWithTwoImagesSlice,
      ContentWithTwoImagesSliceDefaultPrimary,
      ContentWithTwoImagesSliceVariation,
      ContentWithTwoImagesSliceDefault,
      CoreValuesSlice,
      CoreValuesSliceVariation,
      CoreValuesSliceDefault,
      CoreValuesSidebarContentSlice,
      CoreValuesSidebarContentSliceVariation,
      CoreValuesSidebarContentSliceDefault,
      EngageSidebarContentSlice,
      EngageSidebarContentSliceVariation,
      EngageSidebarContentSliceDefault,
      EngageWithUsSlice,
      EngageWithUsSliceVariation,
      EngageWithUsSliceDefault,
      FaqSidebarContentSlice,
      FaqSidebarContentSliceVariation,
      FaqSidebarContentSliceDefault,
      FaqSliceSlice,
      FaqSliceSliceDefaultPrimaryFaqQuestionsItem,
      FaqSliceSliceDefaultPrimary,
      FaqSliceSliceVariation,
      FaqSliceSliceDefault,
      FeaturedImageSlice,
      FeaturedImageSliceDefaultPrimary,
      FeaturedImageSliceVariation,
      FeaturedImageSliceDefault,
      FocusSectorsSlice,
      FocusSectorsSliceVariation,
      FocusSectorsSliceDefault,
      HeroSlice,
      HeroSliceVariation,
      HeroSliceDefault,
      ImageBackgroundSlice,
      ImageBackgroundSliceDefaultPrimary,
      ImageBackgroundSliceVariation,
      ImageBackgroundSliceDefault,
      IndustriesOfInterestSlice,
      IndustriesOfInterestSliceVariation,
      IndustriesOfInterestSliceDefault,
      InsightIndexSlice,
      InsightIndexSliceVariation,
      InsightIndexSliceDefault,
      MemberBioSliceSlice,
      MemberBioSliceSliceDefaultPrimary,
      MemberBioSliceSliceVariation,
      MemberBioSliceSliceDefault,
      OneImageBackgroundSlice,
      OneImageBackgroundSliceDefaultPrimary,
      OneImageBackgroundSliceVariation,
      OneImageBackgroundSliceDefault,
      ServicesSlice,
      ServicesSliceDefaultPrimary,
      ServicesSliceServicesWithHeadingPrimary,
      ServicesSliceVariation,
      ServicesSliceDefault,
      ServicesSliceServicesWithHeading,
      ServicesColoredSectionSlice,
      ServicesColoredSectionSliceVariation,
      ServicesColoredSectionSliceDefault,
      ServicesSidebarContentSlice,
      ServicesSidebarContentSliceDefaultPrimary,
      ServicesSidebarContentSliceVariation,
      ServicesSidebarContentSliceDefault,
      SidebarContentSlice,
      SidebarContentSliceDefaultPrimary,
      SidebarContentSliceVariation,
      SidebarContentSliceDefault,
      SlideShowSlice,
      SlideShowSliceVariation,
      SlideShowSliceDefault,
      TeamIndexSlice,
      TeamIndexSliceDefaultPrimaryTeamMembersItem,
      TeamIndexSliceDefaultPrimary,
      TeamIndexSliceVariation,
      TeamIndexSliceDefault,
      TestimonialsSlice,
      TestimonialsSliceVariation,
      TestimonialsSliceDefault,
      TestimonialsSidebarContentSlice,
      TestimonialsSidebarContentSliceVariation,
      TestimonialsSidebarContentSliceDefault,
      VideoBackgroundSlice,
      VideoBackgroundSliceDefaultPrimary,
      VideoBackgroundSliceVariation,
      VideoBackgroundSliceDefault,
      VisionMissionSlice,
      VisionMissionSliceDefaultPrimary,
      VisionMissionSliceVariation,
      VisionMissionSliceDefault,
      WhyChooseUsSlice,
      WhyChooseUsSliceDefaultPrimary,
      WhyChooseUsSliceVariation,
      WhyChooseUsSliceDefault,
      WhyUsSlice,
      WhyUsSliceVariation,
      WhyUsSliceDefault,
    };
  }
}
