// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  call_to_action: dynamic(() => import("./CallToAction")),
  contact_form: dynamic(() => import("./ContactForm")),
  contact_hero: dynamic(() => import("./ContactHero")),
  content_heading: dynamic(() => import("./ContentHeading")),
  faq_slice: dynamic(() => import("./FaqSlice")),
  featured_image: dynamic(() => import("./FeaturedImage")),
  focus_sectors: dynamic(() => import("./FocusSectors")),
  hero: dynamic(() => import("./Hero")),
  image_background: dynamic(() => import("./ImageBackground")),
  insight_index: dynamic(() => import("./InsightIndex")),
  member_bio_slice: dynamic(() => import("./MemberBioSlice")),
  services: dynamic(() => import("./Services")),
  video_background: dynamic(() => import("./VideoBackground")),
  why_choose_us: dynamic(() => import("./WhyChooseUs")),
};
