// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  call_to_action: dynamic(() => import("./CallToAction")),
  color_background: dynamic(() => import("./ColorBackground")),
  contact_form: dynamic(() => import("./ContactForm")),
  contact_hero: dynamic(() => import("./ContactHero")),
  content_heading: dynamic(() => import("./ContentHeading")),
  content_with_two_images: dynamic(() => import("./ContentWithTwoImages")),
  core_values: dynamic(() => import("./CoreValues")),
  core_values_sidebar_content: dynamic(
    () => import("./CoreValuesSidebarContent"),
  ),
  engage_sidebar_content: dynamic(() => import("./EngageSidebarContent")),
  engage_with_us: dynamic(() => import("./EngageWithUs")),
  faq_sidebar_content: dynamic(() => import("./FaqSidebarContent")),
  faq_slice: dynamic(() => import("./FaqSlice")),
  featured_image: dynamic(() => import("./FeaturedImage")),
  file_input_slice: dynamic(() => import("./FileInputSlice")),
  focus_sectors: dynamic(() => import("./FocusSectors")),
  hero: dynamic(() => import("./Hero")),
  image_background: dynamic(() => import("./ImageBackground")),
  industries_of_interest: dynamic(() => import("./IndustriesOfInterest")),
  insight_index: dynamic(() => import("./InsightIndex")),
  member_bio_slice: dynamic(() => import("./MemberBioSlice")),
  one_image_background: dynamic(() => import("./OneImageBackground")),
  services: dynamic(() => import("./Services")),
  services_accordian: dynamic(() => import("./ServicesAccordian")),
  services_colored_section: dynamic(() => import("./ServicesColoredSection")),
  services_sidebar_content: dynamic(() => import("./ServicesSidebarContent")),
  sidebar_content: dynamic(() => import("./SidebarContent")),
  slide_show: dynamic(() => import("./SlideShow")),
  team_index: dynamic(() => import("./TeamIndex")),
  testimonials: dynamic(() => import("./Testimonials")),
  testimonials_sidebar_content: dynamic(
    () => import("./TestimonialsSidebarContent"),
  ),
  video_background: dynamic(() => import("./VideoBackground")),
  vision_mission: dynamic(() => import("./VisionMission")),
  why_choose_us: dynamic(() => import("./WhyChooseUs")),
  why_us: dynamic(() => import("./WhyUs")),
};
